"""add tags to faq

Revision ID: 9591956ba938
Revises: 4b2e301b3e82
Create Date: 2026-03-06 10:05:16.690033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9591956ba938'
down_revision: Union[str, Sequence[str], None] = '4b2e301b3e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faq_items', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faq_items', 'tags')
    # ### end Alembic commands ###
